# Generated by Django 5.1.2 on 2024-10-13 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('envelopeno', models.IntegerField(blank=True, null=True, verbose_name='Envelope number')),
                ('clc_addr_id', models.IntegerField(blank=True, null=True)),
                ('prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('addr1', models.CharField(blank=True, max_length=32, null=True)),
                ('addr2', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(blank=True, max_length=32, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('lastupdate', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=64, null=True)),
                ('updateby', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.CharField(blank=True, default='Y', max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('special_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('occasion', models.CharField(blank=True, max_length=32, null=True)),
                ('processed_date', models.DateTimeField(blank=True, max_length=32, null=True)),
                ('batch', models.IntegerField(blank=True, null=True)),
                ('lastupdate', models.DateTimeField(blank=True, max_length=32, null=True)),
                ('updateby', models.CharField(blank=True, max_length=20, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giving.donor')),
            ],
        ),
    ]
