# Generated by Django 5.1.2 on 2024-10-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address_type', models.CharField(max_length=1, verbose_name='Address Category')),
                ('directorytype', models.CharField(default='m', max_length=1, verbose_name='Directory Category')),
                ('advent', models.CharField(blank=True, max_length=2, null=True)),
                ('envelopeno', models.IntegerField(blank=True, null=True, verbose_name='Envelope number')),
                ('prefix', models.CharField(blank=True, max_length=40, null=True)),
                ('lastname', models.CharField(blank=True, max_length=40, null=True, verbose_name='Last name')),
                ('firstname', models.CharField(blank=True, max_length=40, null=True, verbose_name='First name')),
                ('suffix', models.CharField(blank=True, max_length=40, null=True)),
                ('addrline1', models.CharField(blank=True, max_length=40, null=True, verbose_name='Address line1')),
                ('addrline2', models.CharField(blank=True, max_length=40, null=True, verbose_name='Address line2')),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('state', models.CharField(blank=True, max_length=40, null=True)),
                ('country', models.CharField(blank=True, max_length=40, null=True)),
                ('postalcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Zip')),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('family', models.CharField(blank=True, max_length=40, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('cell1', models.CharField(blank=True, max_length=32, null=True)),
                ('cell2', models.CharField(blank=True, max_length=32, null=True)),
                ('archive', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('lastupdate', models.DateTimeField(blank=True, null=True, verbose_name='Last Update')),
                ('updateby', models.CharField(blank=True, max_length=20, null=True, verbose_name='Updated by')),
            ],
        ),
    ]
