# Generated by Django 5.1.2 on 2024-10-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sort_name', models.CharField(max_length=32)),
                ('first_name', models.CharField(blank=True, default='', max_length=20, verbose_name='First Names')),
                ('addr_name1', models.CharField(max_length=32, verbose_name='Address Name1')),
                ('addr_name2', models.CharField(blank=True, default='', max_length=32, verbose_name='Address Name2')),
                ('addr_line1', models.CharField(max_length=32, verbose_name='Address Line1')),
                ('addr_line2', models.CharField(blank=True, max_length=32, verbose_name='Address Line2')),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(blank=True, max_length=40, null=True)),
                ('zip', models.CharField(blank=True, max_length=20, null=True)),
                ('phone1', models.CharField(blank=True, max_length=30, null=True)),
                ('phone2', models.CharField(blank=True, max_length=30, null=True)),
                ('e_mail', models.CharField(blank=True, max_length=64, null=True, verbose_name='e-mail2')),
                ('notes1', models.CharField(blank=True, max_length=128, null=True)),
                ('notes2', models.CharField(blank=True, max_length=128, null=True)),
                ('map_num', models.CharField(max_length=15, verbose_name='Map number')),
                ('fire_num', models.IntegerField(verbose_name='Fire Number')),
                ('rd_section', models.CharField(max_length=16, verbose_name='Road Name')),
                ('purchase_date', models.CharField(blank=True, max_length=10, null=True)),
                ('rhha', models.BooleanField()),
                ('billable', models.BooleanField()),
                ('archive', models.BooleanField()),
                ('lastupdate', models.DateTimeField(blank=True, null=True, verbose_name='Last Update')),
                ('updateby', models.CharField(blank=True, max_length=20, null=True, verbose_name='Updated By')),
            ],
        ),
    ]
