alter table dbsk_donations
    alter column id drop identity
;

alter table dbsk_donations
    alter column id
        set generated by default as identity (start with 600 increment by 1 minvalue 600 maxvalue 2000000000 no cycle cache 20 no order)
;
alter table dbsk_donations primary key (id);