# Generated by Django 5.1.2 on 2024-10-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EV6',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(max_length=10)),
                ('odometer', models.IntegerField()),
                ('new_miles', models.IntegerField()),
                ('kwh', models.IntegerField(blank=True, null=True)),
                ('full_charge', models.BooleanField()),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
