# Generated by Django 5.1.2 on 2024-10-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ev6',
            name='kwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
