# Generated by Django 5.1.2 on 2024-10-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('energy', '0003_alter_ev6_kwh'),
    ]

    operations = [
        migrations.AddField(
            model_name='ev6',
            name='mkwh',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
