# Generated by Django 5.1.2 on 2024-10-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('energy', '0004_ev6_mkwh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ev6',
            name='kwh',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ev6',
            name='mkwh',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True),
        ),
    ]
