# Generated by Django 5.1.2 on 2024-10-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('energy', '0005_alter_ev6_kwh_alter_ev6_mkwh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electrical',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(max_length=10)),
                ('kwh', models.IntegerField()),
                ('meter_reading', models.IntegerField()),
                ('solar_balance', models.IntegerField()),
                ('estimated', models.BooleanField(blank=True, null=True)),
                ('ch_base', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ch_delivery', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ch_supply', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ch_prev', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ch_curr', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ch_adjustment', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ch_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ch_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('lastupdate', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=32, null=True)),
                ('updateby', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
