# Generated by Django 5.1.2 on 2024-10-12 20:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('energy', '0006_electrical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electrical',
            name='estimated',
        ),
    ]
