# Generated by Django 5.1.2 on 2024-10-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('energy', '0007_remove_electrical_estimated'),
    ]

    operations = [
        migrations.AddField(
            model_name='ev6',
            name='miles_per_kwh',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=5, null=True),
        ),
    ]
