# Generated by Django 5.1.2 on 2024-11-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('energy', '0008_ev6_miles_per_kwh'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(max_length=10)),
                ('solar_kwh', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('max_kwh', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('main_a', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('main_b', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('main_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('mini_split', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('garage_a', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('garage_b', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('garage_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('solar', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('ev', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
            ],
        ),
    ]
