# Generated by Django 5.1.2 on 2024-10-14 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('addr1', models.CharField(blank=True, max_length=32, null=True)),
                ('addr2', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(blank=True, max_length=32, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=32, null=True)),
                ('lastupdate', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=32, null=True)),
                ('updateby', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.CharField(blank=True, default='Y', max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=32)),
                ('contact_name', models.CharField(blank=True, max_length=20, null=True)),
                ('preferred_day', models.CharField(blank=True, max_length=20, null=True)),
                ('addr1', models.CharField(blank=True, max_length=40, null=True, verbose_name='Address line 1')),
                ('addr2', models.CharField(blank=True, max_length=40, null=True, verbose_name='Address line 2')),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('phone1', models.CharField(default='None', max_length=32)),
                ('phone2', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(blank=True, max_length=32, null=True)),
                ('notes', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('lastupdate', models.DateTimeField(blank=True, null=True)),
                ('updateby', models.CharField(blank=True, max_length=20, null=True)),
                ('archive', models.CharField(default='N', max_length=1)),
            ],
            options={
                'ordering': ('archive', 'provider_name'),
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20, verbose_name='First name')),
                ('lastname', models.CharField(max_length=20, verbose_name='Last name')),
                ('addr1', models.CharField(blank=True, max_length=40, null=True, verbose_name='Address line 1')),
                ('addr2', models.CharField(blank=True, max_length=40, null=True, verbose_name='Address line 2')),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('phone1', models.CharField(default='None', max_length=32)),
                ('phone2', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(blank=True, max_length=32, null=True)),
                ('preferred_contact', models.CharField(blank=True, default='P', max_length=1, null=True)),
                ('notes', models.CharField(blank=True, max_length=120, null=True)),
                ('availability', models.CharField(blank=True, max_length=16, null=True)),
                ('lastupdate', models.DateTimeField(blank=True, null=True)),
                ('updateby', models.CharField(blank=True, max_length=20, null=True)),
                ('archive', models.CharField(default='N', max_length=1)),
            ],
            options={
                'ordering': ('archive', 'lastname'),
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('check_no', models.CharField(blank=True, max_length=16, null=True)),
                ('check_date', models.DateField(blank=True, max_length=12, null=True)),
                ('occasion', models.CharField(blank=True, max_length=32, null=True)),
                ('processed_date', models.DateTimeField(blank=True, max_length=32, null=True)),
                ('batch', models.IntegerField(blank=True, null=True)),
                ('lastupdate', models.DateTimeField(blank=True, max_length=32, null=True)),
                ('updateby', models.CharField(blank=True, max_length=20, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbsk.donor')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(verbose_name='date scheduled')),
                ('s_year', models.IntegerField(blank=True, null=True)),
                ('s_month', models.IntegerField(blank=True, null=True)),
                ('s_day', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(max_length=40, null=True)),
                ('lastupdate', models.DateTimeField(blank=True, null=True)),
                ('updateby', models.CharField(blank=True, max_length=20, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider',
                                               to='dbsk.provider')),
                ('volunteer1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='volunteer1',
                                                 to='dbsk.volunteer')),
                ('volunteer2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='volunteer2',
                                                 to='dbsk.volunteer')),
            ],
        ),
    ]
