# Generated by Django 5.1.2 on 2024-10-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dbsk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorVw',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('addr1', models.CharField(blank=True, max_length=32, null=True)),
                ('addr2', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(blank=True, max_length=32, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('processed_date', models.DateTimeField(blank=True, max_length=32, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('active', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'dbsk_donorvw',
                'managed': False,
            },
        ),
    ]
