# Generated by Django 5.1.2 on 2024-10-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DwaAddr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('xmas', models.CharField(blank=True, max_length=1, null=True)),
                ('lastname', models.CharField(blank=True, max_length=20, null=True)),
                ('addr_name', models.CharField(blank=True, max_length=34, null=True)),
                ('addrline1', models.CharField(blank=True, max_length=40, null=True)),
                ('addrline2', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('state', models.CharField(blank=True, max_length=40, null=True)),
                ('country', models.CharField(blank=True, max_length=40, null=True)),
                ('postalcode', models.CharField(blank=True, max_length=20, null=True)),
                ('phone1', models.CharField(blank=True, max_length=32, null=True)),
                ('phone2', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True, verbose_name='e-mail')),
                ('name1', models.CharField(blank=True, max_length=20, null=True)),
                ('name2', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.CharField(blank=True, max_length=128, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('lastupdate', models.DateTimeField(blank=True, null=True)),
                ('updateby', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, default='A', max_length=1, null=True)),
                ('archive', models.CharField(blank=True, default='N', max_length=1, null=True)),
            ],
        ),
    ]
