# Generated by Django 5.1.3 on 2025-10-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaddr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('service', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=40)),
                ('notes', models.CharField(blank=True, max_length=128, null=True)),
                ('lastupdate', models.DateTimeField(blank=True, null=True)),
                ('updateby', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
